# Generated by Django 5.2 on 2025-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/%y/%m/%d')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('response', models.TextField()),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
