# Generated by Django 5.2 on 2025-05-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_message_created_at_message_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.JSONField(blank=True),
        ),
    ]
