# Generated by Django 5.2 on 2025-05-04 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'mp4', 'mov', 'avi', 'mp3', 'wav'])], verbose_name='فایل')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('alt_text', models.CharField(blank=True, help_text='متن توصیفی برای دسترسی پذیری و SEO', max_length=255, verbose_name='متن جایگزین')),
                ('caption', models.TextField(blank=True, verbose_name='توضیح')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], max_length=10, verbose_name='نوع فایل')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
            ],
            options={
                'db_table': 'media_files',
            },
        ),
    ]
