# Generated by Django 5.2 on 2025-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='alt_text',
            field=models.CharField(blank=True, help_text='متن توصیفی برای دسترسی پذیری و SEO', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
